
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalisisUsuarios;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int USUARIO = 5;
  public static final int EOF = 0;
  public static final int MAYOR_Q = 3;
  public static final int DIAGONAL = 4;
  public static final int CONTRASENIA = 7;
  public static final int MENOR_Q = 2;
  public static final int error = 1;
  public static final int NOMBRE = 6;
  public static final int IDENTIFICADOR = 8;
  public static final int PASSWORD = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MENOR_Q",
  "MAYOR_Q",
  "DIAGONAL",
  "USUARIO",
  "NOMBRE",
  "CONTRASENIA",
  "IDENTIFICADOR",
  "PASSWORD"
  };
}

