
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIAGONAL = 4;
  public static final int ALINEACION = 40;
  public static final int BORRAR_PAGINA = 21;
  public static final int PAGINA = 33;
  public static final int PARAMETROS = 13;
  public static final int NOMBRE = 11;
  public static final int ENTERO = 54;
  public static final int DATO = 50;
  public static final int ANCHO = 47;
  public static final int ORACION = 51;
  public static final int IZQUIERDA = 42;
  public static final int VIDEO = 37;
  public static final int ETIQUETAS = 15;
  public static final int FECHA = 52;
  public static final int MENU = 38;
  public static final int IDENTIFICADOR = 48;
  public static final int IGUAL = 6;
  public static final int CENTRAR = 41;
  public static final int TITULO = 30;
  public static final int ID_ETIQUETA = 53;
  public static final int PADRE = 32;
  public static final int MAYOR_Q = 3;
  public static final int ID = 25;
  public static final int NUEVA_PAGINA = 19;
  public static final int EOF = 0;
  public static final int BORRAR_COMPONENTE = 24;
  public static final int MENOR_Q = 2;
  public static final int CLASE = 34;
  public static final int error = 1;
  public static final int COMILLA = 5;
  public static final int FECHA_MODIFICACION = 28;
  public static final int URL = 56;
  public static final int ATRIBUTOS = 8;
  public static final int BORRAR_SITIO_WEB = 18;
  public static final int ATRIBUTO = 7;
  public static final int ACCION = 9;
  public static final int COLOR = 45;
  public static final int USUARIO_MODIFICACION = 29;
  public static final int FECHA_CREACION = 27;
  public static final int NUEVO_SITIO_WEB = 17;
  public static final int USUARIO_CREACION = 26;
  public static final int VALOR = 16;
  public static final int DERECHA = 43;
  public static final int IMAGEN = 36;
  public static final int ORIGEN = 49;
  public static final int PARRAFO = 35;
  public static final int MODIFICAR_COMPONENTE = 23;
  public static final int AGREGAR_COMPONENTE = 22;
  public static final int HEXADECIMAL = 55;
  public static final int PARAMETRO = 12;
  public static final int ACCIONES = 10;
  public static final int SITIO = 31;
  public static final int TEXTO = 39;
  public static final int ETIQUETA = 14;
  public static final int ALTURA = 46;
  public static final int JUSTIFICAR = 44;
  public static final int MODIFICAR_PAGINA = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MENOR_Q",
  "MAYOR_Q",
  "DIAGONAL",
  "COMILLA",
  "IGUAL",
  "ATRIBUTO",
  "ATRIBUTOS",
  "ACCION",
  "ACCIONES",
  "NOMBRE",
  "PARAMETRO",
  "PARAMETROS",
  "ETIQUETA",
  "ETIQUETAS",
  "VALOR",
  "NUEVO_SITIO_WEB",
  "BORRAR_SITIO_WEB",
  "NUEVA_PAGINA",
  "MODIFICAR_PAGINA",
  "BORRAR_PAGINA",
  "AGREGAR_COMPONENTE",
  "MODIFICAR_COMPONENTE",
  "BORRAR_COMPONENTE",
  "ID",
  "USUARIO_CREACION",
  "FECHA_CREACION",
  "FECHA_MODIFICACION",
  "USUARIO_MODIFICACION",
  "TITULO",
  "SITIO",
  "PADRE",
  "PAGINA",
  "CLASE",
  "PARRAFO",
  "IMAGEN",
  "VIDEO",
  "MENU",
  "TEXTO",
  "ALINEACION",
  "CENTRAR",
  "IZQUIERDA",
  "DERECHA",
  "JUSTIFICAR",
  "COLOR",
  "ALTURA",
  "ANCHO",
  "IDENTIFICADOR",
  "ORIGEN",
  "DATO",
  "ORACION",
  "FECHA",
  "ID_ETIQUETA",
  "ENTERO",
  "HEXADECIMAL",
  "URL"
  };
}

